### ISSUE TITLE
Can't balance `Mg+O2=C+MgO`

### ISSUE THREAD

**Issue by LEXUGE** [XCH-CEB/lib-xch-ceb#3]
# Excepted behaviors:
`Mg+O2=C+MgO` => `2Mg+O2=C+2MgO`
# Current behaviors:
`Mg+O2=C+MgO` => `NoAnswer`
# Steps to reproduce behaviors:
Just use API simply to reproduce it.

**Comment by TaikiAkita** [comment]
2Mg+O2=2MgO

**Comment by LEXUGE** [comment]
@TaikiAkita 

> 2Mg+O2=2MgO
The carbon "C" is useless and should be deleted from the output equation.

However, Mg can be burned in CO2. And the equation is legal. So I think it should be balanced without extra processes.

**Comment by LEXUGE** [comment]
Oops, I made a stupid mistake.
It's alright.
It should be `Mg+CO2=MgO+C` => `2Mg+CO2=2MgO+C`
